version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - pydoc-markdown --build --site-dir "$READTHEDOCS_OUTPUT/html"

python:
  install:
  - requirements: requirements.txt

sphinx:
  configuration: ./source/conf.py