version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands: 
      - mkdir --parents _readthedocs/html/
      - cp --recursive build/html/* _readthedocs/html/

python:
  install:
  - requirements: requirements.txt

sphinx:
  configuration: ./source/conf.py